name: CI
on:

  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a multi-line script
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          git clone https://github.com/danny-keizer/PARAMI.git

          uv run main.py create entry --file terraform.tfvars
          uv run main.py --attribute id --search all
