name: CI
on:

  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Parami
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          git clone https://github.com/danny-keizer/Parami.git && cd Parami
          uv tool install .


      - name: Run Commands
        run: |
          parami create entry --file terraform.tfvars
          parami read entry --attribute id --search all
